### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by LievreAI** [cyphina/UnboundedPerceptions#2]
i using ue 4.24.3 visual studio 2019 building configration is "Development Editor" "Win64"
once i press build i have got error "Could not find definition for module 'BLU', (refrenced via Target -> MyProjectEditor.Build.cs - > MyProject.Build.cs

**Comment by cyphina** [comment]
Yea sorry this project also uses the plugin [BLUI ](https://github.com/getnamo/BLUI/releases) (I haven't updated my project to 4.27) so the version of BLUI for 4.26 should work.
